{
 "title": "Xiaomi Sensors",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "location",
    "label": "Location",
    "query": "SELECT distinct(location) FROM sensors WHERE device = 'LYWSD03MMC' AND active = true ORDER BY location;"
   }
  ]
 },
 "panels": [
  {
   "title": "Live",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  location,\n  AVG(value) OVER(ORDER BY location,time ROWS BETWEEN 4 PRECEDING AND CURRENT ROW)\nFROM live JOIN sensors ON live.sensor_id = sensors.id AND\n  type = 'temperature'\nWHERE\n  $__timeFilter(time) AND location IN ($location)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Humidity",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  location,\n  AVG(value) OVER(ORDER BY location,time ROWS BETWEEN 4 PRECEDING AND CURRENT ROW)\nFROM live JOIN sensors ON live.sensor_id = sensors.id AND\n  type = 'humidity'\nWHERE\n  $__timeFilter(time) AND location IN ($location)\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Temperature",
     "type": "bargauge",
     "gridPos": { "h": 20, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  location,\n  value AS temp\nFROM live JOIN sensors ON live.sensor_id = sensors.id AND\n  type = 'temperature'\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1;"
      }
     ]
    },
    {
     "title": "Humidity",
     "type": "bargauge",
     "gridPos": { "h": 20, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  location,\n  value AS hum\nFROM live JOIN sensors ON live.sensor_id = sensors.id AND\n  type = 'humidity'\nWHERE\n  $__timeFilter(time)\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Sensor Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Battery Level",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  location,\n  value AS bat\nFROM live JOIN sensors ON live.sensor_id = sensors.id AND\n  type = 'battery-level'\nWHERE\n  $__timeFilter(time)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Signal Strength",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "dB" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  location,\n  --AVG(value) OVER(ORDER BY location,time ROWS BETWEEN 4 PRECEDING AND CURRENT ROW)\n  value\nFROM live JOIN sensors ON live.sensor_id = sensors.id AND\n  type = 'rssi-value'\nWHERE\n  $__timeFilter(time) AND location IN ($location)\nORDER BY 1"
      }
     ]
    }
   ]
  }
 ]
}