esphome:
  name: nodemcu
  platform: ESP32
  board: nodemcu-32s 

wifi:
  ssid: "Your SSID"
  password: "Your wifi password"

api:

ota:

logger:

esp32_ble_tracker:
  scan_parameters:
    window: 120ms

web_server:
  port: 80

mqtt:
  broker: 192.168.178.27
  username: mqtt
  password: "Your broker password"

sensor:
  - platform: uptime
    name: "Nodemcu Uptime"
    filters:
    - throttle: 10min

  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:8C:34:B7"
    bindkey: "fe39106baeedb7c801e3d63c4396f97e"
    temperature:
      name: "Piano Temperature"
    humidity:
      name: "Piano Humidity"
    battery_level:
      name: "Piano Battery-Level"
  - platform: ble_rssi
    mac_address: "A4:C1:38:8C:34:B7"
    name: "Piano RSSI-value"
    filters:
    - median:
        window_size: 60
        send_every: 60
        send_first_at: 1

  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:BC:B9:B2"
    bindkey: "66c0f070f7394bb753e11198e3061830"
    temperature:
      name: "Kitchen Temperature"
    humidity:
      name: "Kitchen Humidity"
    battery_level:
      name: "Kitchen Battery-Level"
  - platform: ble_rssi
    mac_address: "A4:C1:38:BC:B9:B2"
    name: "Kitchen RSSI-value"
    filters:
    - median:
        window_size: 60
        send_every: 60
        send_first_at: 1

  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:B1:CD:7F"
    bindkey: "eef418daf699a0c188f3bfd17e4565d9"
    temperature:
      name: "Patio Temperature"
    humidity:
      name: "Patio Humidity"
    battery_level:
      name: "Patio Battery-Level"
  - platform: ble_rssi
    mac_address: "A4:C1:38:B1:CD:7F"
    name: "Piano RSSI-value"
    filters:
    - median:
        window_size: 60
        send_every: 60
        send_first_at: 1

